services:
  mongo-db:
   image: mongo:latest
   container_name: mongo-db
   ports:
    - "27017:27017"
   volumes:
    - mongo-data:/data/db
   environment:
    - MONGO_INITDB_ROOT_USERNAME=assignment
    - MONGO_INITDB_ROOT_PASSWORD=healthychef
   restart: always

volumes:
  mongo-data: